articles/urls.py
# articles/urls.py
from django.urls import path
from .views import user_login, user_register, dashboard,article_detail,edit_article,delete_article,user_logout,add_article


urlpatterns = [
    path('login/', user_login, name='login'),
    path('register/', user_register, name='register'),
    path('dashboard/', dashboard, name='dashboard'),
    path('article/<int:article_id>/', article_detail, name='article_detail'),
    path('edit/<int:article_id>/', edit_article, name='edit_article'),
    path('delete/<int:article_id>/', delete_article, name='delete_article'),
    path('logout/', user_logout, name='logout'),
    path('add/', add_article, name='add_article'),
    path('',user_login,name="default")
    # Add other URLs as needed
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    publication_date = models.DateTimeField(auto_now_add=True)
    tags = models.CharField(max_length=100, blank=True)
    file = models.FileField(upload_to='article_files/', null=True, blank=True)


    def __str__(self):
        return self.title

articles/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'tags', 'file']
        widgets = {
            'content': CKEditorWidget(),
        }

articles/views.py
from django.shortcuts import render, redirect
from django.shortcuts import  get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Article
from .forms import ArticleForm
from django.db.models import Q
from django.contrib.auth import logout
from django.shortcuts import redirect
   

@login_required
def user_logout(request):
    logout(request)
    messages.success(request,"logout Succesfull")
    return redirect('login') 

def user_login(request):
    if request.user.is_authenticated:
        return redirect('dashboard')  
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Login successful.')
            return redirect('dashboard')  
        else:
            messages.error(request, 'Invalid login credentials.')
    return render(request, 'login.html')

def user_register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            print("form is valid")
            messages.success(request, 'Registration successful. You can now log in.')
            return redirect('login')
        else:
            messages.error(request, form.errors)
        
    else:
        form = UserCreationForm()

    return render(request, 'register.html', {'form': form})


@login_required
def dashboard(request):
    articles_list = Article.objects.all()
    #get user
    

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            messages.success(request,"Post Succesfull")
            return redirect('dashboard')
        else:
            messages.error(request,form.errors)
 
    else:
        
        query = request.GET.get('q')
        filter_option = request.GET.get('filter_option')  
        articles = Article.objects.all()
        filter_mapping = {
            'title': 'title__icontains',
            'content': 'content__icontains',
            'tags': 'tags__icontains',
            'author': 'author__username__icontains',
        }

        # Check if the selected filter option is valid
        if filter_option in filter_mapping and query is not None:
            articles_list = articles.filter(**{filter_mapping[filter_option]: query})

        form = ArticleForm()

    # Pagination
    paginator = Paginator(articles_list, 3)  
    page = request.GET.get('page')

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    return render(request, 'dashboard.html',  {'articles': articles, 'form': form})

@login_required
def article_detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    print(request.user.is_staff)
    return render(request, 'article_detail.html', {'article': article})
@login_required
def edit_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if (not request.user.is_staff and request.user != article.author):
            messages.error(request, 'You are not authorized to delete this article .')
            return redirect('article_detail', article_id=article_id)
        if form.is_valid():
            form.save()
            messages.success(request,"Post Edited Succesfully")
            # Redirect to the updated article detail page
            return redirect('article_detail', article_id=article_id)
    else:
        form = ArticleForm(instance=article)

    return render(request, 'edit_article.html', {'form': form, 'article': article})
@login_required
def delete_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    article_title = article.title  

    if request.method == 'POST' and (request.user.is_staff or request.user == article.author):
        article.delete()
        messages.success(request, f'The article "{article_title}" has been deleted.')
        return redirect('dashboard')
    elif (not request.user.is_staff and request.user != article.author):
        messages.error(request, 'You are not authorized to delete this article .')
        return redirect('article_detail', article_id=article_id)

    return render(request, 'delete_article.html', {'article': article})

@login_required
def add_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            messages.success(request,"Post Succesfull")
            return redirect('dashboard')
        else:
            messages.error(request,form.errors)
 
    else:
        form = ArticleForm()
    return render(request, 'new_article.html', {'form': form})

templates/article_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{{ article.title }} - Article Detail</title>
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <style>
      .custom {
        margin-left: 20px;
      }
    </style>
  </head>
  <body>
    {% if messages %}
    <div
      class="alert alert-dismissible {% if messages.tags %}{{ messages.tags }}{% endif %}"
    >
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {% for message in messages %} {{ message }} {% endfor %}
    </div>
    {% endif %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">{{ article.title }}</h2>
                <p class="card-text">{{ article.content|safe }}</p>

                {% if article.file %}
                <div class="mt-3">
                    <h4>Attached Files:</h4>
                    <ul>
                        <li>
                            <a href="{{ article.file.url }}" target="_blank">{{ article.file.name }}</a>
                        </li>
                    </ul>
                </div>
                {% endif %}

                <p class="card-text">
                    <small class="text-muted">
                        Author: {{ article.author.username }} | Published on: {{ article.publication_date }}
                    </small>
                </p>

                {% if user.is_authenticated and user == article.author or user.is_staff %}
                <div class="btn-group">
                    <a href="{% url 'edit_article' article.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'delete_article' article.id %}" class="btn btn-danger custom" onclick="return confirmDelete();">Delete</a>

                    <script>
                        function confirmDelete() {
                            return confirm("Are you sure you want to delete this article?");
                        }
                    </script>
                </div>
                {% endif %}
            </div>
        </div>
        <a href="{% url 'dashboard' %}" class="btn btn-primary mt-3">Back to Dashboard</a>
    </div>
</body>


    <!-- Bootstrap JS and dependencies (jQuery and Popper.js) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Blog{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  crossorigin="anonymous">
    <script src="https://cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>

    <style>
        .form-group {
            margin-bottom: 20px;
        }
    
        label {
            font-weight: bold;
        }
    
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }
    
        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
    </style>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #007bff;
            color: #ffffff;
            padding: 10px;
            text-align: center;
        }

        nav {
            margin-top: 10px;
        }

        nav ul {
            list-style: none;
            padding: 0;
            margin: 0;
            display: flex;
            justify-content: center;
        }

        nav ul li {
            margin-right: 20px;
        }

        main {
            padding: 20px;
        }

        footer {
            background-color: #007bff;
            color: #ffffff;
            padding: 10px;
            text-align: center;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    {% if messages %}
    <div
      class="alert alert-dismissible {% if messages.tags %}{{ messages.tags }}{% endif %}"
    >
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {% for message in messages %} {{ message }} {% endfor %}
    </div>
    {% endif %}
    

    <main>
        {% block content %}{% endblock %}
    </main>

   
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- CKEditor JS -->
    <script src="https://cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>

</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Blog Dashboard</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .article-form {
            display: none;
        }
    </style>
<script src="https://cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>
</head>
<body>
    {% if messages %}
    <div
      class="alert alert-dismissible {% if messages.tags %}{{ messages.tags }}{% endif %}" style="background-color: rgb(116, 184, 224);"
    >
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {% for message in messages %} {{ message }} {% endfor %}
    </div>
    {% endif %}
<div class="container mt-5">
    <h2>Welcome to the Blog  <a href="{% url 'dashboard' %}">Dashboard!</a></h2>


    <!-- <button class="btn btn-primary mt-3" data-toggle="modal" data-target="#articleModal" style="margin-bottom: 5px;">Add a New Article</button> -->
    <a href="{% url 'add_article' %}" class="btn btn-primary" >Add New Post</a>
    <a href="{% url 'logout' %}" class="btn btn-danger" style="flex-direction: column;     position: absolute;
    right: 20%;">Logout</a>

<form method="get" action="{% url 'dashboard' %}">
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="filterOption">Filter by:</label>
            <select class="form-control" id="filterOption" name="filter_option">
                <option value="title" {% if filter_option == 'title' %}selected{% endif %}>Title</option>
                <option value="content" {% if filter_option == 'content' %}selected{% endif %}>Content</option>
                <option value="tags" {% if filter_option == 'tags' %}selected{% endif %}>Tags</option>
                <option value="author" {% if filter_option == 'author' %}selected{% endif %}>Author</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="query">Search:</label>
            <input type="text" class="form-control" id="query" name="q" value="{{ query }}">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Apply Filters</button>
</form>


    {% if articles %}
        <ul class="list-group mt-3">
            {% for article in articles %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text">{{ article.content|safe|slice:":200" }}</p>
                <p class="card-text">Author: {{ article.author.username }}</p>
                <p class="card-text">Publication Date: {{ article.publication_date }}</p>
                <p class="card-text">Tags: {{article.tags}}</p>
                <a href="{% url 'article_detail' article.id %}" class="btn btn-primary">Read More</a>
            </div>
        </div>
    {% endfor %}
        </ul>

     
        {% else %}
        <p>No articles available.</p>
    {% endif %}
    <div class="mt-3">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
    
                {% if articles.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">&laquo; first</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ articles.previous_page_number }}">previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&laquo; first</span>
                    </li>
                    <li class="page-item disabled">
                        <span class="page-link">previous</span>
                    </li>
                {% endif %}
    
                <li class="page-item disabled">
                    <span class="page-link">Page {{ articles.number }} of {{ articles.paginator.num_pages }}</span>
                </li>
    
                {% if articles.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ articles.next_page_number }}">next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ articles.paginator.num_pages }}">last &raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">next</span>
                    </li>
                    <li class="page-item disabled">
                        <span class="page-link">last &raquo;</span>
                    </li>
                {% endif %}
    
            </ul>
        </nav>
    </div>
    </div>

    <!-- <div class="modal" id="articleModal" tabindex="-1" role="dialog" aria-labelledby="articleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="articleModalLabel">Add a New Article</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{% url 'dashboard' %}" class="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Title</label>
                            <input type="text" id="id_title" name="title" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_content">Content</label>
                            <textarea id="id_content" name="content" class="form-control ckeditor"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="id_tags">Tags</label>
                            <input type="text" id="id_tags" name="tags" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="id_file">File</label>
                            <input type="file" id="id_file" name="file" class="form-control-file">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        CKEDITOR.replace('id_content', {
            customConfig: '/static/js/ckeditor_config.js',  // Adjust the path based on your project
        });
    </script> -->
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>
    <script>
        function toggleForm() {
            $(".article-form").toggle();
        }
    </script>

    
    

</body>
</html>

templates/delete_article.html
<!-- dashboard/delete_article.html -->

{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Warning!</h4>
        <p>Are you sure you want to delete the article "{{ article.title }}"?</p>
        <hr>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes, delete</button>
            <a href="{% url 'dashboard' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/edit_article.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header bg-primary text-white">
            <h2 class="mb-0">Edit Article</h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input type="text" id="id_title" name="title" value="{{ article.title }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_content">Content</label>
                    <textarea id="id_content" name="content" class="form-control">{{ article.content }}</textarea>
                </div>
                <div class="form-group">
                    <label for="id_tags">Tags</label>
                    <input type="text" id="id_tags" name="tags" value="{{ article.tags }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_file">File</label>
                    <input type="file" id="id_file" name="file" class="form-control-file">
                    {% if article.file %}
                        <p class="mt-2">Current File: <a href="{{ article.file.url }}" target="_blank">{{ article.file.name }}</a></p>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary">Save Changes</button>
            </form>
        </div>
    </div>
</div>

<script>
    CKEDITOR.replace('id_content', {
        customConfig: '/static/js/ckeditor_config.js',  // Adjust the path based on your project
    });
</script>
{% endblock %}

templates/login.html
<!-- articles/templates/login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url('https://pbwebdev.co.uk/wp-content/uploads/2018/12/blogs.jpg');
            background-size: cover;
            background-repeat: no-repeat; 
            background-color: #f8f9fa;
            color: #495057;
            padding: 50px;
        }
        .container {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 0px 20px 0px rgba(0,0,0,0.1);
            width: 25%;
            margin-top: 100px;
        }
        .form-group {
            margin-bottom: 20px;
            margin-left: 20px;
            width: 80%;
        }
        label {
            color: #007bff;
        }
        .form-control {
            height: 38px;
            font-size: 14px;
        }
        .btn-success {
            margin-left: 20px;
            background-color: #28a745;
            border-color: #28a745;
        }
        .btn-success:hover {
            background-color: #218838;
            border-color: #218838;
        }
        .btn-primary {
            margin-left: 20px;
        }
        .alert {
        background-color: #dc3545; /* Red background color */
        color: #fff; /* White text color */
        border-color: #dc3545; /* Red border color */
      }
    </style>
</head>
<body>

{% if messages %}
    <div class="alert alert-dismissible {% if messages.tags %}{{ messages.tags }}{% endif %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}

<div class="container">
    <h2 class="mb-4" style="margin-left:150px">Login</h2>

    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>

        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>

        <button type="submit" class="btn btn-primary">Login</button>
    </form>

    <p class="mt-3" style="margin-left: 20px;">Don't have an account? <a href="{% url 'register' %}">Register here</a>.</p>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/new_article.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header bg-primary text-white">
            <h2 class="mb-0">Add Article</h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input type="text" id="id_title" name="title" value="" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_content">Content</label>
                    <textarea id="id_content" name="content" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label for="id_tags">Tags</label>
                    <input type="text" id="id_tags" name="tags" value="{{ article.tags }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_file">File</label>
                    <input type="file" id="id_file" name="file" class="form-control-file">

                </div>
                <button type="submit" class="btn btn-primary">Save Changes</button>
            </form>
        </div>
    </div>
</div>

<script>
    CKEDITOR.replace('id_content', {
        customConfig: '/static/js/ckeditor_config.js',  // Adjust the path based on your project
    });
</script>
{% endblock %}

templates/register.html
<!-- articles/templates/register.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Register</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <style>
      body {
        background-image: url("https://www.theedublogger.com/files/2019/03/10-Minute-Weekly-Blogging-Plan-tasqn3-prizg4-1080x720.jpeg");
        background-size: cover;
        background-repeat: no-repeat;
        background-color: #f8f9fa;
        color: #495057;
        padding: 50px;
      }
      .container {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.1);
        width: 30%;
        margin-top: 100px;
      }
      .form-group {
        margin-bottom: 20px;
        margin-left: 20px;
        width: 80%;
      }
      label {
        color: #007bff;
      }
      .form-control {
        height: 38px;
        font-size: 14px;
      }
      .btn-success {
        margin-left: 20px;
        background-color: #28a745;
        border-color: #28a745;
      }
      .btn-success:hover {
        background-color: #218838;
        border-color: #218838;
      }
      .alert {
        background-color: #dc3545; /* Red background color */
        color: #fff; /* White text color */
        border-color: #dc3545; /* Red border color */
      }
    </style>
  </head>
  <body>
    {% if messages %}
    <div
      class="alert alert-dismissible {% if messages.tags %}{{ messages.tags }}{% endif %}"
    >
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {% for message in messages %} {{ message }} {% endfor %}
    </div>
    {% endif %}

    <div class="container">
      <h2 class="mb-4">Register</h2>

      <form method="post" action="{% url 'register' %}">
        {% csrf_token %}

        <div class="form-group">
          <label for="username">Username:</label>
          <input
            type="text"
            class="form-control"
            id="username"
            name="username"
            required
          />
        </div>

        <div class="form-group">
          <label for="password1">Password:</label>
          <input
            type="password"
            class="form-control"
            id="password1"
            name="password1"
            required
          />
        </div>

        <div class="form-group">
          <label for="password2">Confirm Password:</label>
          <input
            type="password"
            class="form-control"
            id="password2"
            name="password2"
            required
          />
        </div>

        <button type="submit" class="btn btn-success">Register</button>
      </form>

      <p class="mt-3" style="margin-left: 20px">
        Already have an account? <a href="{% url 'login' %}">Login here</a>.
      </p>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>